apiVersion: skaffold/v4beta9
kind: Config
build:
  # tagPolicy: 
  #   sha256: {}
  artifacts:
    - image: zoodruimage
      context: .
      docker:
        dockerfile: docker/dru/Dockerfile


profiles:
  - name: dru
    deploy:
      helm:
        releases:
          - name: zoo-project-dru
            remoteChart: zoo-project/zoo-project-dru
            namespace: eoap-zoo-project
            createNamespace: true
            version: 0.3.2
            valuesFiles: []
            setValueTemplates:
              iam.enabled: false
              cookiecutter.templateUrl: https://github.com/eoap/zoo-service-template.git
              cookiecutter.templateBranch: develop
              filter_in.enabled: true
              filter_out.enabled: true
              zoofpm.image.repository: "{{.IMAGE_REPO_zoodruimage}}"
              zoofpm.image.tag: "{{.IMAGE_TAG_zoodruimage}}"
              zoofpm.image.pullPolicy: Never
              zookernel.image.repository: "{{.IMAGE_REPO_zoodruimage}}"
              zookernel.image.tag: "{{.IMAGE_TAG_zoodruimage}}"
              zookernel.image.pullPolicy: Never


portForward:
  - resourceType: service
    resourceName: zoo-project-dru-service
    namespace: eoap-zoo-project  
    address: localhost
    port: 80
    localPort: 8080  