name: Publish Docker image to AWS ECR

on:

 push:
   tags:
     - 'eodhp-[0-9]+'
     - 'eodhp-[0-9]+-*'
     - 'eodhp-[0-9]+.[0-9]+'
     - 'eodhp-[0-9]+.[0-9]+-*'
     - 'eodhp-[0-9]+.[0-9]+.[0-9]+'
     - 'eodhp-[0-9]+.[0-9]+.[0-9]+-*'
   branches:
     - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get image tag
        id: get-image-tag
        run: |
          IMAGE_TAG=$(if [[ "${GITHUB_REF##refs/tags/}" =~ ^v ]]; then echo ${GITHUB_REF##refs/tags/v}; elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then echo "latest"; else echo "${GITHUB_REF##refs/heads/}-latest" | sed "s/[^a-zA-Z0-9]/-/g" ; fi) >> "$GITHUB_ENV"
          echo $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-container-registry
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ inputs.AWS_ACCOUNT_ID }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials

      - name: Docker login
        id: docker-login
        shell: bash
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR }}

        # This will cache Docker layers.
        # We could also cache the cache mounts used in the Dockerfile but do not,
        # see https://docs.docker.com/build/ci/github-actions/cache/
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AWS_ECR }}/zoo-project-dru:${{ env.VERSION_TAG }}
          build-args: |
            GIT_REF_NAME=${{ github.ref_name }}
            GIT_SHA=${{ github.sha }}
          context: .
          file: docker/dru/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max