name: Documentation building and deployment 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  documentation-build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Documentation using sphinx Docker image
      run: |
        docker run --rm -v $(pwd)/docs:/docs sphinxdoc/sphinx make html ;
        sudo touch docs/_build/html/.nojekyll ;
        sudo cp docs/_config.yml docs/_build/html/
    - name: Build the Documentation using doxygen Docker image
      run: |
        docker run --rm -v $(pwd)/zoo-project/zoo-kernel:/data hrektts/doxygen doxygen  ;
        sudo cp -r zoo-project/zoo-kernel/html docs/_build/html/C_API
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs/_build/html
